fisco:
  cryptoMaterial:
    certPath: "conf"
  #  caCert: "conf/ca.crt"
  #  sslCert: "conf/sdk.crt"
  #  sslKey: "conf/sdk.key"
  #  enSslCert: "conf/gm/gmensdk.crt"
  #  enSslKey: "conf/gm/gmensdk.key"

  network:
    peers:
      - "106.12.221.38:20201"
      - "106.12.221.38:20200"

  amop:
  #  - publicKeys: [ "conf/amop/consumer_public_key_1.pem" ]
  #    topicName: "PrivateTopic1"
  #  - password: "123456"
  #    privateKey: "conf/amop/consumer_private_key.p12"
  #    topicName: "PrivateTopic2"

  account:
    keyStoreDir: "account"
    #  accountFilePath: "conf"
    accountFileFormat: "pem"
  #  accountAddress: "0x"
  #  password: ""

  threadPool:
  #  channelProcessorThreadSize: "16"
  #  receiptProcessorThreadSize: "16"
    maxBlockingQueueSize: "102400"